# Generated by Django 3.2.7 on 2021-09-30 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SetData', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='category_status',
        ),
        migrations.AddField(
            model_name='unit',
            name='unit_status',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='categoryproduct',
            name='category_status',
            field=models.IntegerField(default=1),
        ),
    ]
