# Generated by Django 3.2.7 on 2021-09-30 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SetData', '0002_auto_20210930_1125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tickercode',
            name='ticker_code_id',
        ),
    ]
