# Generated by Django 3.2.7 on 2021-09-30 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SetData', '0003_remove_tickercode_ticker_code_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickercode',
            name='category',
            field=models.CharField(default='CTGR', max_length=5),
        ),
        migrations.AlterField(
            model_name='tickercode',
            name='customer',
            field=models.CharField(default='CTM', max_length=5),
        ),
        migrations.AlterField(
            model_name='tickercode',
            name='goods_delivery_note',
            field=models.CharField(default='GDN', max_length=5),
        ),
        migrations.AlterField(
            model_name='tickercode',
            name='goods_received_note',
            field=models.CharField(default='GRN', max_length=5),
        ),
        migrations.AlterField(
            model_name='tickercode',
            name='inventory_sheet',
            field=models.CharField(default='IS', max_length=5),
        ),
        migrations.AlterField(
            model_name='tickercode',
            name='invoice',
            field=models.CharField(default='IV', max_length=5),
        ),
        migrations.AlterField(
            model_name='tickercode',
            name='order',
            field=models.CharField(default='OD', max_length=5),
        ),
        migrations.AlterField(
            model_name='tickercode',
            name='partner',
            field=models.CharField(default='PN', max_length=5),
        ),
        migrations.AlterField(
            model_name='tickercode',
            name='product',
            field=models.CharField(default='PD', max_length=5),
        ),
        migrations.AlterField(
            model_name='tickercode',
            name='service',
            field=models.CharField(default='SV', max_length=5),
        ),
        migrations.AlterField(
            model_name='tickercode',
            name='shipping_unit',
            field=models.CharField(default='SU', max_length=5),
        ),
        migrations.AlterField(
            model_name='tickercode',
            name='unit',
            field=models.CharField(default='UN', max_length=5),
        ),
        migrations.AlterField(
            model_name='tickercode',
            name='user',
            field=models.CharField(default='US', max_length=5),
        ),
        migrations.AlterField(
            model_name='tickercode',
            name='vendor',
            field=models.CharField(default='VD', max_length=5),
        ),
    ]
