# Generated by Django 3.2.7 on 2021-09-30 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SetData', '0004_auto_20210930_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickercode',
            name='category',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='tickercode',
            name='customer',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='tickercode',
            name='goods_delivery_note',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='tickercode',
            name='goods_received_note',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='tickercode',
            name='inventory_sheet',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='tickercode',
            name='invoice',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='tickercode',
            name='order',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='tickercode',
            name='partner',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='tickercode',
            name='product',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='tickercode',
            name='service',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='tickercode',
            name='shipping_unit',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='tickercode',
            name='unit',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='tickercode',
            name='user',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='tickercode',
            name='vendor',
            field=models.CharField(max_length=5),
        ),
    ]
