# Generated by Django 3.2.7 on 2021-10-06 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('STT', models.BigAutoField(primary_key=True, serialize=False)),
                ('partner_id', models.CharField(max_length=10)),
                ('partner_name', models.TextField()),
                ('partner_sex', models.IntegerField()),
                ('partner_image', models.TextField()),
                ('store_name', models.TextField()),
                ('store_image', models.TextField()),
                ('partner_phone', models.CharField(max_length=11)),
                ('partner_phone2', models.CharField(max_length=11)),
                ('partner_CMND', models.CharField(max_length=20)),
                ('partner_CMND_date_created', models.DateField()),
                ('partner_CMND_addres', models.TextField()),
                ('partner_CMND_issued', models.TextField()),
                ('partner_birthday', models.DateField()),
                ('partner_CMND_image_front', models.TextField()),
                ('partner_CMND_image_back', models.TextField()),
                ('partner_email', models.TextField()),
                ('partner_address', models.TextField()),
                ('partner_area', models.TextField()),
                ('partner_province', models.TextField()),
                ('partner_district', models.TextField()),
                ('partner_wards', models.TextField()),
                ('partner_recruitment_source', models.IntegerField()),
                ('police_certificate', models.TextField()),
                ('partner_bank_account', models.TextField()),
                ('bank_name', models.TextField()),
                ('bank_account_holder_name', models.CharField(max_length=255)),
                ('partner_slug', models.CharField(max_length=255)),
                ('partner_status', models.IntegerField(default=1)),
                ('partner_desc', models.TextField()),
                ('partner_coin', models.IntegerField()),
                ('partner_total_order', models.IntegerField(default=0)),
                ('partner_total_revenue', models.IntegerField(default=0)),
                ('partner_total_profit', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
