# Generated by Django 3.2.7 on 2021-10-06 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Partner', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partner',
            old_name='partner_CMND_addres',
            new_name='partner_CMND_address',
        ),
        migrations.AlterField(
            model_name='partner',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='partner',
            name='partner_recruitment_source',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='partner',
            name='partner_status',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='partner',
            name='partner_total_order',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='partner',
            name='partner_total_profit',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='partner',
            name='partner_total_revenue',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='partner',
            name='updated_at',
            field=models.DateTimeField(),
        ),
    ]
