# Generated by Django 3.2.7 on 2021-10-06 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Partner', '0002_auto_20211006_2235'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeRepair',
            fields=[
                ('STT', models.BigAutoField(primary_key=True, serialize=False)),
                ('type_vehicle', models.CharField(max_length=10)),
                ('partner_stt', models.IntegerField()),
                ('status', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
        ),
    ]
