# Generated by Django 3.2.7 on 2021-10-07 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Partner', '0003_typerepair'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='password',
            field=models.CharField(default=123, max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partner',
            name='username',
            field=models.TextField(default=123),
            preserve_default=False,
        ),
    ]
