# Generated by Django 3.2.7 on 2021-10-11 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Partner', '0004_auto_20211007_2223'),
    ]

    operations = [
        migrations.CreateModel(
            name='districts',
            fields=[
                ('STT', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('gso_id', models.TextField()),
                ('province_id', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Provinces',
            fields=[
                ('STT', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('gso_id', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Wards',
            fields=[
                ('STT', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('gso_id', models.TextField()),
                ('district_id', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
        ),
    ]
