# Generated by Django 3.2.7 on 2021-10-11 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Partner', '0005_districts_provinces_wards'),
    ]

    operations = [
        migrations.RenameField(
            model_name='districts',
            old_name='STT',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='provinces',
            old_name='STT',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='wards',
            old_name='STT',
            new_name='id',
        ),
    ]
