# Generated by Django 3.2.7 on 2021-10-12 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Partner', '0006_auto_20211011_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provinces',
            name='created_at',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='provinces',
            name='gso_id',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='provinces',
            name='name',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='provinces',
            name='updated_at',
            field=models.DateTimeField(blank=True),
        ),
    ]
