# Generated by Django 3.2.7 on 2021-10-16 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Partner', '0007_auto_20211012_2117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partner',
            old_name='partner_name',
            new_name='partner_firstname',
        ),
        migrations.AddField(
            model_name='partner',
            name='bank_branch',
            field=models.TextField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='partner_lastname',
            field=models.TextField(null=True, unique=True),
        ),
    ]
