# Generated by Django 3.2.7 on 2021-10-16 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Partner', '0008_auto_20211016_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='bank_branch',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='partner_lastname',
            field=models.TextField(null=True),
        ),
    ]
