# Generated by Django 3.2.7 on 2021-10-16 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Partner', '0009_auto_20211016_1718'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TypeRepair',
        ),
        migrations.AddField(
            model_name='partner',
            name='typerepair_xedap',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='typerepair_xehoi',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='typerepair_xekeo',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='typerepair_xemay',
            field=models.IntegerField(null=True),
        ),
    ]
