# Generated by Django 3.2.7 on 2021-10-16 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Partner', '0010_auto_20211016_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='partner_CMND_image_back',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='partner',
            name='partner_CMND_image_front',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='partner',
            name='partner_image',
            field=models.FileField(upload_to='static/fileupload/'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='partner_sex',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='store_image',
            field=models.FileField(upload_to=''),
        ),
    ]
