# Generated by Django 3.2.7 on 2021-10-16 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Partner', '0011_auto_20211016_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='store_image',
            field=models.FileField(upload_to='static/fileupload/'),
        ),
    ]
