# Generated by Django 3.2.7 on 2021-10-16 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Partner', '0012_alter_partner_store_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='partner_CMND_image_back',
            field=models.FileField(upload_to='static/fileupload/'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='partner_CMND_image_front',
            field=models.FileField(upload_to='static/fileupload/'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='police_certificate',
            field=models.FileField(upload_to='static/fileupload/'),
        ),
    ]
