# Generated by Django 3.2.7 on 2021-10-17 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Partner', '0013_auto_20211016_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='partner_CMND_image_back',
            field=models.FileField(blank=True, upload_to='static/fileupload/'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='partner_CMND_image_front',
            field=models.FileField(blank=True, upload_to='static/fileupload/'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='partner_image',
            field=models.FileField(blank=True, upload_to='static/fileupload/'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='police_certificate',
            field=models.FileField(blank=True, upload_to='static/fileupload/'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='store_image',
            field=models.FileField(blank=True, upload_to='static/fileupload/'),
        ),
    ]
