# Generated by Django 3.2.7 on 2021-10-17 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Partner', '0014_auto_20211017_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='partner_CMND_image_back',
            field=models.ImageField(blank=True, upload_to='static/fileupload/'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='partner_CMND_image_front',
            field=models.ImageField(blank=True, upload_to='static/fileupload/'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='partner_image',
            field=models.ImageField(blank=True, upload_to='static/fileupload/'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='store_image',
            field=models.ImageField(blank=True, upload_to='static/fileupload/'),
        ),
    ]
