# Generated by Django 3.2.7 on 2021-10-17 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Partner', '0015_auto_20211017_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='partner_CMND_image_back',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='partner',
            name='partner_CMND_image_front',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='partner',
            name='partner_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='partner',
            name='police_certificate',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='partner',
            name='store_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
