# Generated by Django 3.2.7 on 2021-10-26 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Partner', '0017_cancelpartner_changeinfopartner_ticket_withdrawalslip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='confirm_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
